In [444]:
%reset
import pandas as pd
import numpy as np
import scipy.stats as stats
import matplotlib.pyplot as plt
from sklearn.metrics import f1_score

train1 = pd.read_csv('train_dataset01.csv')
train2 = pd.read_csv('train_dataset02.csv')
test = pd.read_csv('test_dataset.csv')

Once deleted, variables cannot be recovered. Proceed (y/[n])? y

In [445]:
train2.head()

,DATETIME,LEVEL_T1,LEVEL_T2,LEVEL_T3,LEVEL_T4,LEVEL_T5,LEVEL_T6,LEVEL_T7,PRESSURE_J280,PRESSURE_J269,PRESSURE_J300,PRESSURE_J256,PRESSURE_J289,PRESSURE_J415,PRESSURE_J302,PRESSURE_J306,PRESSURE_J307,PRESSURE_J317,PRESSURE_J14,PRESSURE_J422,FLOW_PU1,FLOW_PU2,FLOW_PU3,FLOW_PU4,FLOW_PU5,FLOW_PU6,FLOW_PU7,FLOW_PU8,FLOW_PU9,FLOW_PU10,FLOW_PU11,FLOW_V2,STATUS_PU1,STATUS_PU2,STATUS_PU3,STATUS_PU4,STATUS_PU5,STATUS_PU6,STATUS_PU7,STATUS_PU8,STATUS_PU9,STATUS_PU10,STATUS_PU11,STATUS_V2,ATT_FLAG
0,2016-02-04 05:00:00,1.40,3.81,4.96,4.04,4.5,5.02,2.71,2.98,35.33,29.34,75.98,29.30,87.96,25.31,112.55,25.19,71.13,31.86,30.96,95.61,95.63,0.0,0.0,0.0,0.0,49.32,12.01,0.0,31.23,0.0,79.61,True,True,False,False,False,False,True,True,False,True,False,True,False
1,2016-02-04 05:15:00,1.45,3.89,4.91,4.16,4.5,5.11,2.94,2.98,35.36,29.41,75.92,29.37,88.07,25.36,112.60,25.24,71.29,31.93,31.03,95.56,95.58,0.0,0.0,0.0,0.0,49.29,12.01,0.0,31.20,0.0,79.40,True,True,False,False,False,False,True,True,False,True,False,True,False
2,2016-02-04 05:30:00,1.49,3.97,4.85,4.29,4.5,5.20,3.17,2.98,35.39,29.48,75.87,29.44,88.19,25.41,112.65,25.29,71.45,32.00,31.10,95.51,95.52,0.0,0.0,0.0,0.0,49.27,12.01,0.0,31.16,0.0,79.19,True,True,False,False,False,False,True,True,False,True,False,True,False
3,2016-02-04 05:45:00,1.53,4.05,4.80,4.42,4.5,5.30,3.40,2.98,35.41,29.55,75.81,29.51,88.30,25.46,112.70,25.34,71.62,32.07,31.17,95.45,95.47,0.0,0.0,0.0,0.0,49.25,12.01,0.0,31.13,0.0,78.98,True,True,False,False,False,False,True,True,False,True,False,True,False
4,2016-02-04 06:00:00,1.57,4.12,4.74,4.55,4.5,5.39,3.63,2.98,35.32,31.73,75.16,31.73,67.28,24.74,109.86,24.63,71.12,33.98,33.08,95.62,95.64,0.0,0.0,0.0,0.0,0.00,15.59,0.0,31.07,0.0,61.06,True,True,False,False,False,False,False,True,False,True,False,True,False

In [446]:
# Function to create new features
def make_new_features(data, fluc_window, MA_window, above_window, cat_window, means):
    """
    Fluctions refer to the sum of differences
    between each row and its previous row in a window
    """
    numerics = data.select_dtypes(include="float64")
    booleans = data.select_dtypes(include="bool")
    
    # Calculate fluctuations
    flucs = numerics.diff()
    flucs = flucs.abs()
    flucs = flucs.rolling(fluc_window).sum()
    flucs = flucs.fillna(0)
    flucs.columns = [str(col) + '_delta_t' for col in flucs.columns]
    
    # Calculate Moving Average
    ma = numerics.rolling(MA_window).mean()
    ma = ma.fillna(numerics.mean())
    ma.columns = [str(col) + '_MA' for col in ma.columns]
    
    # Count number of obs above mean in a window
    above = numerics > means
    above = above.rolling(above_window).sum()
    above = above.fillna(above.mean())
    above.columns = [str(col) + '_above' for col in above.columns]
    
#     # Count number of trues in a window
#     trues = booleans.rolling(cat_window).sum()
#     trues = trues.fillna(trues.mean())
#     trues.columns = [str(col) + '_counts' for col in trues.columns]
    
    # Create output
    out = pd.concat([data.reset_index(drop=True), flucs], axis=1)
    out = pd.concat([out.reset_index(drop=True), ma], axis=1)
    out = pd.concat([out.reset_index(drop=True), above], axis=1)
#     out = pd.concat([out.reset_index(drop=True), trues], axis=1)

    return out

In [447]:
# Function to calculate p-value for every obs
def make_p_values(data, means, stds):
    """
    Calculate p-value for all obs for all numeric 
    features
    """
    numeric_cols = data.select_dtypes(include="float64").columns
    new_cols = []
    for col in numeric_cols:
        new_col = col + "_p"
        
        # Calculate p-values
        data[new_col] = data[col].apply(stats.norm.cdf, 
                                        args=(means[col], stds[col]))
        
        # Make values between 0 and 0.5
        data[new_col] = np.where(data[new_col] <= 0.5, data[new_col], 1 - data[new_col])
        data[new_col] = data[new_col].fillna(0.5)
        new_cols.append(new_col)

    return new_cols

In [448]:
# Function to vote anomalies from p-values
def create_votes(data, p_cols, threshold):
    """
    For each p-value column, add 1 vote if p-value below threshold
    Votes decide whether an obs is an anomaly
    """
    temp = data[test_p_cols] < threshold
    data["votes"] = temp.sum(axis=1)

In [449]:
# Function to get scores from votes
def create_scores(data, alpha):
    """
    Create score from votes
    Each score depends on all previous scores
    """
    scores = []
    for i in range(len(data["votes"])):
        if i > 1:
            score = alpha*scores[i-1] + data["votes"][i]
        else:
            score = data["votes"][i]
        scores.append(score)
    return scores

In [450]:
# Function to change scores to ATT_FLAG
def create_ATT_FLAG(data, scores, min_votes):
    """
    Create dataframe in submission format
    """
    temp = np.asarray(scores)

    out = data[["DATETIME"]].copy()
    out["ATT_FLAG"] = np.where(temp >= min_votes, 1, 0)

    return out

In [451]:
def frange(x, y, jump):
    """
    range for floats
    """
    while x < y:
        yield x
        x += jump

In [452]:
def log_progress(sequence, every=None, size=None, name='Items'):
    from ipywidgets import IntProgress, HTML, VBox
    from IPython.display import display

    is_iterator = False
    if size is None:
        try:
            size = len(sequence)
        except TypeError:
            is_iterator = True
    if size is not None:
        if every is None:
            if size <= 200:
                every = 1
            else:
                every = int(size / 200)     # every 0.5%
    else:
        assert every is not None, 'sequence is iterator, set every'

    if is_iterator:
        progress = IntProgress(min=0, max=1, value=1)
        progress.bar_style = 'info'
    else:
        progress = IntProgress(min=0, max=size, value=0)
    label = HTML()
    box = VBox(children=[label, progress])
    display(box)

    index = 0
    try:
        for index, record in enumerate(sequence, 1):
            if index == 1 or index % every == 0:
                if is_iterator:
                    label.value = '{name}: {index} / ?'.format(
                        name=name,
                        index=index
                    )
                else:
                    progress.value = index
                    label.value = u'{name}: {index} / {size}'.format(
                        name=name,
                        index=index,
                        size=size
                    )
            yield record
    except:
        progress.bar_style = 'danger'
        raise
    else:
        progress.bar_style = 'success'
        progress.value = index
        label.value = "{name}: {index}".format(
            name=name,
            index=str(index or '?')
        )

In [453]:
# Learn mean and std from no attack data
no_attacks = train2[~train2.ATT_FLAG]
means = no_attacks.mean()
stds = no_attacks.std()

# Process train2
train2 = make_new_features(train2, 10, 10, 20, 20, means)

# Process test
test = make_new_features(test, 10, 10, 20, 20, means)

# Update mean and std with new features
no_attacks = train2[~train2.ATT_FLAG]
means = no_attacks.mean()
stds = no_attacks.std()

# Make p-value columns
train_p_cols = make_p_values(train2, means, stds)
test_p_cols = make_p_values(test, means, stds)

In [491]:
# Grid Search for best p-value threshold, decay rate and min_vote
bestF1 = 0
bestP = 0
bestAlpha = 0
bestMinVotes = 0
y_true = train2.ATT_FLAG

for iteration in log_progress(range(30), every=1):
    p = 0.003 + iteration*0.0001
    create_votes(train2, train_p_cols, p)

    for alpha in frange(0.94, 0.99, 0.002):
        train2_scores = create_scores(train2, alpha)

        for min_votes in range(85, 110):            
            train2_out = create_ATT_FLAG(train2, train2_scores, min_votes)

            # Calculate F score in train2
            y_pred = train2_out.ATT_FLAG == 1
            f1 = f1_score(y_true, y_pred)
            
            if f1 > bestF1:
                bestF1 = f1
                bestP = p
                bestAlpha = alpha
                bestMinVotes = min_votes
                
print(bestF1, bestP, bestAlpha, bestMinVotes)
# 0.735 0.0150 0.970 94  with fluc (0.015 P was my lower bound)
# 0.751 0.0120 0.955 96  with fluc and ma (0.012 P was my lower bound)
# 0.780 0.0060 0.970 99  with fluc, ma and above (0.005 P was my lower bound)
# 0.781 0.0057 0.969 91  with fluc, ma and above (0.005 P was my lower bound)
# 0.764 0.0055 0.972 113 with fluc, ma, above and cat_counts (0.005 P was my lower bound)

# 0.772 0.0039 0.976 115 with fluc, ma, above, cat_counts and 20,20 windows
# 0.786 0.0034 0.972 87  with fluc, ma, above and 20,20 windows (0.0034 P was my lower bound)

VBox(children=(HTML(value=''), IntProgress(value=0, max=30)))

0.7860020140986909 0.0034000000000000002 0.972 87

In [455]:
create_votes(test, test_p_cols, bestP)

In [456]:
test_scores = create_scores(test, bestAlpha)

In [457]:
test_out = create_ATT_FLAG(test, test_scores, bestMinVotes)

In [477]:
create_votes(train2, train_p_cols, 0.0034)
train2_scores = create_scores(train2, 0.972)
train2_out = create_ATT_FLAG(train2, train2_scores, 87)

y_pred = train2_out.ATT_FLAG == 1
f1 = f1_score(y_true, y_pred)
f1

0.7860020140986909

In [1]:
# Plot
fig, ax1 = plt.subplots(figsize=(20, 10))

color = 'tab:blue'
ax1.set_xlabel('time')
ax1.set_ylabel('PRESSURE_J300', color=color)
ax1.plot(test['PRESSURE_J300'], color=color)

ax2 = ax1.twinx()  # instantiate a second axes that shares the same x-axis
color = 'tab:red'
ax2.plot(test_out['ATT_FLAG'], color=color)

plt.show()

NameError: name 'plt' is not defined

In [460]:
test_out["ATT_FLAG"] = test_out["ATT_FLAG"].astype('bool')
test_out.head()

              DATETIME  ATT_FLAG
0  2016-09-18 04:45:00     False
1  2016-09-18 05:00:00     False
2  2016-09-18 05:15:00     False
3  2016-09-18 05:30:00     False
4  2016-09-18 05:45:00     False

In [461]:
# test_out.to_csv("output3.csv", index=False)